### ISSUE TITLE
We need CI integration for this repo

### ISSUE THREAD

**Issue by hrasadi** [googleinterns/cloudevents-sdk-cpp#5]
We need to integrate with a CI solution so that our tests run automatically when we merge new PRs.

**Comment by michlee1337** [comment]
PR #11 sets up the config files for Travis CI, but an owner of the main repo will need to activate Travis CI tracking on their Travis CI account.

It's really easy, just need to 
1. Make an account at the [Travis CI website](https://github.com/googleinterns/cloudevents-sdk-cpp/pull/travis-ci.org/) with the same Github account that owns the CE-SDK-CPP repository, 
2. Navigate to the repository list on the Travis CI webiste, and 
3. Activate CI on the CE-SDK-CPP repository.

**Comment by hrasadi** [comment]
Done. Closing this issue.
